- name: create fabric nodes
  hosts: apic
  connection: local
  gather_facts: no
  tasks:
   - name: firmware group
     aci_firmware_group:
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: no
        group: test
        firmwarepol: test
        state: present