- name: create fabric nodes
  hosts: apic
  connection: local
  gather_facts: no
  tasks:
   - name: add firmware group node
     aci_firmware_group_node:
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: no
       group: test
       node: 1001
       state: present