- name: create fabric nodes
  hosts: apic
  connection: local
  gather_facts: no
  tasks:
   - name: maintenance group
     aci_maintenance_group:
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: no
       group: test
       policy: test
       state: present