- name: create fabric nodes
  hosts: apic
  connection: local
  gather_facts: no
  tasks:
  - name: maintenance group
    aci_maintenance_group_node:
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: no
      group: EVEN
      node: 1002
      state: present
